version: "3.7"

services:

  # app:
  #   image: mcr.microsoft.com/dotnet/sdk:${DOTNET_TAG}
  #   hostname: app
  #   stop_grace_period: 60s
  #   restart: always
  #   environment:
  #     DB: $DB
  #   build: 
  #     context: ./EntityFrameworkExample
  #     args:
  #       DB: $DB
  #       DOTNET_TAG: $DOTNET_TAG
  #   ports:
  #     - ${DOTNET_PORT}:80 

  postgres:
    image: "postgres:${POSTGRES_TAG}"
    container_name: "${PROJECT_NAME}-postgres"
    hostname: postgres
    restart: unless-stopped
    stop_grace_period: 60s
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    image: "adminer:${ADMINER_TAG}"
    container_name: "${PROJECT_NAME}-adminer"
    stop_grace_period: 5s
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
      
  sqlitebrowser:
    image: "lscr.io/linuxserver/sqlitebrowser:${SQLITE_BROWSER_TAG}"
    container_name: "${PROJECT_NAME}-sqlitebrowser"
    security_opt:
      - seccomp:unconfined  
    stop_grace_period: 5s
    restart: unless-stopped
    ports:
      - ${SQLITE_BROWSER_PORT}:3000
    volumes:
      - ./EntityFrameworkExample:/app

networks:
  default:
      name: $PROJECT_NAME
