version: "3.7"

services:

  postgres:
    image: "postgres:${POSTGRES_TAG}"
    container_name: "${PROJECT_NAME}-postgres"
    hostname: postgres
    restart: always
    stop_grace_period: 60s
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    image: "adminer:${ADMINER_TAG}"
    container_name: "${PROJECT_NAME}-adminer"
    stop_grace_period: 60s
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

networks:
  default:
      name: $PROJECT_NAME
